paths:
  /api/v1/products/:
    get:
      tags:
        - Products
      summary: Obtener todos los productos
      responses:
        200:
          description: OK
  /api/v1/products/{productsId}:
      get:
        tags:
          - Products
        summary: Obtener un producto por su ID
        parameters:
          - name: productsId
            in: path
            description: ID del producto a obtener
            required: true
            type: string
        responses:
          200:
            description: OK
      delete:
        tags:
          - Products
        summary: Eliminar un producto por su ID
        parameters:
          - name: productsId
            in: path
            description: ID del producto a eliminar
            required: true
            type: string
        responses:
          200:
            description: OK
      put:
        tags:
          - Products
        summary: Actualizar un producto por su ID
        parameters:
          - name: productsId
            in: path
            description: ID del producto a actualizar
            required: true
            type: string
        responses:
          200:
            description: OK
  /api/v1/products:
    post:
      tags:
        - Products
      summary: Crear un nuevo producto
      responses:
        200:
          description: OK
